---
title: "git_01"
author: "Rafaela Alcivar"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

A boat beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July —  
Children three that nestle near,  
Eager eye and willing ear,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

As I came to the edge of the woods,  
Thrush music — hark!  
Now if it was dusk outside,  
Inside it was dark.  

Too dark in the woods for a bird  
By sleight of wing  
To better its perch for the night,  
Though it still could sing.  

The last of the light of the sun  
That had died in the west  
Still lived for one song more  
In a thrush's breast.  

Far in the pillared dark  
Thrush music went —  
Almost like a call to come in  
To the dark and lament.  

But no, I was out for stars;  
I would not come in.  
I meant not even if asked;  
And I hadn't been.  
